##########################################################################
########################## AUTOMATION LOG LEVEL ##########################
##########################################################################
# log levels available to use (defined by java):
## SEVERE (highest value)
## WARNING
## INFO (default)
## CONFIG
## FINE
## FINER
## FINEST  (lowest value)
# additional: 
### ALL to see all logs
### OFF to disable logs
##########################################################################
automation.log.level=FINEST
